# Generated by Django 4.2.1 on 2023-06-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_expenditure_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
    ]
