# Generated by Django 4.2.1 on 2023-06-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='expenditure_type',
            field=models.CharField(default='Default', max_length=30),
        ),
    ]
