# Generated by Django 4.2.1 on 2023-06-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expenditure_expenditure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default=None, max_length=4),
        ),
    ]
