# Generated by Django 4.2.1 on 2023-06-09 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_portfolio_trade_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.portfolio_history'),
        ),
    ]
