# Generated by Django 4.2.1 on 2023-06-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_portfolio_history_portfolio_portfolio_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_history',
            name='stock_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
