# Generated by Django 4.2.1 on 2023-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
