# Generated by Django 4.2.1 on 2023-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_transaction_transaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='monthly_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='quarterly_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='weekly_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='yearly_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
