# Generated by Django 4.2.1 on 2023-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_expenditure_monthly_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
