# Generated by Django 4.2.1 on 2023-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_history',
            name='stock_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
