# Generated by Django 4.2.1 on 2023-05-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_alter_balance_user_alter_expenditure_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
