# Generated by Django 4.2.1 on 2023-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_balance_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
