# Generated by Django 4.2.1 on 2023-05-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_expenditure_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
